# for spring boot to sql server
spring.application.name=demo
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MarketDayDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# for google oauth
google.client-id=${GOOGLE_CLIENT_ID}
# for jwt
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000
